# Generated by Django 5.0.6 on 2024-06-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_task_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='technology',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('css', 'CSS'), ('html', 'HTML'), ('cpp', 'C++'), ('c', 'C'), ('docker', 'Docker'), ('git', 'Git'), ('react', 'React'), ('django', 'Django'), ('php', 'PHP'), ('java', 'Java')], default='Other', max_length=10),
        ),
    ]
